#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/redpig_master?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: P@ssw0rd123!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
##生成的代码存放目录:resources下
#filePlace: tmp
##vm模板存放目录
#vmPlace: generator
#
#serverPath: http://localhost:8001/
#upload: /files